---
groups:
- name: develop
  jobs:
  - build-ui
  - deploy-ui
- name: publish
  jobs:
  - ui-major
  - ui-minor

maven-params: &maven-params
  MAVEN_OPTS: {{maven-opts}}
  MAVEN_CONFIG: {{maven-config}}
  MAVEN_REPO_MIRROR: {{maven-repository-mirror-url}}
  MAVEN_REPO_USERNAME: {{maven-repository-username}}
  MAVEN_REPO_PASSWORD: {{maven-repository-password}}

cf-params: &cf-params
  CF_API_URL: {{cf-api-url}}
  CF_SKIP_SSL: {{cf-skip-ssl}}
  CF_USERNAME: {{cf-username}}
  CF_PASSWORD: {{cf-password}}
  CF_ORG: {{cf-org}}
  CF_SPACE: {{cf-space}}

jobs:
- name: build-ui
  public: true
  plan:
  - aggregate:
    - get: pipeline
    - get: concourse-commons
    - get: project
      resource: aviato-ui
      trigger: true
    - get: version
      resource: ui-version
      params: { pre: rc }
  - task: build
    file: concourse-commons/tasks/build-maven.yml
    params:
      <<: *maven-params
      ARTIFACT_ID: aviato-ui
  - put: ui-milestone
    params:
      file: build-output/aviato-ui-*.jar
      version_file: version/number
  - put: ui-version
    params:
      file: version/number

- name: deploy-ui
  public: true
  serial: true
  plan:
  - aggregate:
    - get: pipeline
    - get: concourse-commons
    - get: release
      resource: ui-milestone
      passed: [ build-ui ]
      trigger: true
  - task: generate-manifest
    file: concourse-commons/tasks/generate-manifest.yml
    params:
      <<: *cf-params
      CF_APP_NAME: {{cf-app-ui-name}}
      CF_APP_HOST: {{cf-app-ui-host}}
      CF_ARTIFACT_ID: aviato-ui
  - put: cf-itest
    params:
      manifest: generate-manifest-output/manifest.yml
      current_app_name: {{cf-app-ui-name}}

- name: ui-major
  public: true
  serial_groups: [ ui-version ]
  plan:
  - get: ui-version
    params: { bump: major, pre: rc }
  - put: ui-version
    params: { file: ui-version/number }

- name: ui-minor
  public: true
  serial_groups: [ ui-version ]
  plan:
  - get: ui-version
    params: { bump: minor, pre: rc }
  - put: ui-version
    params: { file: ui-version/number }

resources:
- name: pipeline
  type: git
  source:
    uri: {{pipeline-git-uri}}
    branch: {{pipeline-git-branch}}

- name: concourse-commons
  type: git
  source:
    uri: {{concourse-commons-git-uri}}
    branch: {{concourse-commons-git-branch}}

- name: aviato-ui
  type: git
  source:
    uri: {{aviato-ui-git-uri}}
    branch: {{aviato-ui-git-branch}}
    private_key: {{git-private-key}}

- name: ui-version
  type: semver
  source:
    driver: git
    uri: {{aviato-ui-version-git-uri}}
    branch: {{aviato-ui-version-git-branch}}
    file: number
    initial_version: 1.0.0-rc.0
    private_key: {{git-private-key}}

- name: ui-milestone
  type: maven-resource
  source:
    url: {{maven-repository-milestone-url}}
    artifact: com.aviato:aviato-ui:jar
    username: {{maven-repository-username}}
    password: {{maven-repository-password}}

# - name: ui-release
#   type: maven-resource
#   source:
#     url: {{maven-repository-release-url}}
#     artifact: com.aviato:aviato-ui:jar
#     username: {{maven-repository-username}}
#     password: {{maven-repository-password}}

- name: cf-itest
  type: cf
  source:
    api: {{cf-api-url}}
    skip_cert_check: true
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: latest
